/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2003 by Argonne National Laboratory and Northwestern University.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by command:
 *     ./buildiface -infile=../../../src/include/pnetcdf.h -deffile=./defs
 * DO NOT EDIT
 */
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-parameter"
#endif
#include "mpinetcdf_impl.h"


/* Prototypes for the Fortran interfaces */
#include "mpifnetcdf.h"

#ifdef F77_NAME_UPPER
#define nfmpi_xinq_libvers_ NFMPI_XINQ_LIBVERS
#elif defined(F77_NAME_LOWER_2USCORE)
#define nfmpi_xinq_libvers_ nfmpi_xinq_libvers__
#elif !defined(F77_NAME_LOWER_USCORE)
#define nfmpi_xinq_libvers_ nfmpi_xinq_libvers
/* Else leave name alone */
#endif

FORTRAN_API int FORT_CALL nfmpi_xinq_libvers_ ( char *v1 FORT_MIXED_LEN(d1) FORT_END_LEN(d1) ){
    const char *p = ncmpi_inq_libvers();
    size_t len = strlen(p);
    /* d1 is the length of the string passed into the routine */
    if (len > (size_t)d1) len = (size_t)d1;  /* MIN(len, d1) */
    memcpy(v1, p, len);
    /* Blank pad */
    if (len < (size_t)d1) memset(v1+len, ' ', (size_t)d1-len);
    return 0;
}
